version: "3.4"

services:

  redis:
    image: redis:4.0.7
    ports:
      - "6379:6379"
    container_name: redis
    hostname: redis
    expose:
      - "6379"
    networks:
      - main

  worker:
    build:
      context: .
    restart: on-failure
    container_name: worker
    command: celery -A geartracker worker -l info
    depends_on:
      - redis
      - web
    hostname: worker
    volumes:
      - .:/code
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    networks:
      - main

  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: web
    hostname: web
    command: gunicorn settings.wsgi -b 0.0.0.0:5000
    volumes:
      - .:/code
    environment:
      PORT: "5000"
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - main

networks:

  main:



