# Generated by Django 2.1.7 on 2019-03-19 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geartracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name_plural': 'Activities'},
        ),
        migrations.AlterModelOptions(
            name='gear',
            options={'verbose_name_plural': 'Gear'},
        ),
        migrations.AddField(
            model_name='gear',
            name='type',
            field=models.CharField(choices=[('frame', 'Frame'), ('front-wheel-hub', 'Front Wheel Hub'), ('rear-wheel-hub', 'Rear Wheel Hub'), ('front-wheel-rim', 'Front Wheel Rim'), ('rear-wheel-rim', 'Rear Wheel Rim'), ('chain', 'Chain'), ('fork', 'Fork'), ('handlebar', 'Handlebar'), ('pedals', 'Pedals'), ('front-tire', 'Front Tire'), ('reat-tire', 'Rear Tire'), ('bottom-bracket', 'Bottom Bracket'), ('front-brake', 'Front Brake'), ('rear-brake', 'Rear Brake'), ('front-brake-pads', 'Front Brake Pads'), ('rear-brake-pads', 'Rear Brake Pads'), ('front-brake-rotor', 'Front Brake Rotor'), ('rear-brake-rotor', 'Rear Brake Rotor'), ('front-brake-cable', 'Front Brake Cable'), ('rear-brake-cable', 'Rear Brake Cable'), ('front-brake-housing', 'Front Brake Housing'), ('rear-brake-housing', 'Rear Brake Housing'), ('front-brake-lever', 'Front Brake Lever'), ('rear-brake-lever', 'Rear Brake Lever'), ('cassette', 'Cassette'), ('chainring', 'Chainring'), ('crankset', 'Crankset'), ('rear-derailleur', 'Rear Derailleur'), ('front-derailleur', 'Front Derailleur'), ('headset', 'Headset'), ('saddle', 'Saddle'), ('seatpost', 'Seatpost'), ('stem', 'Stem'), ('shock', 'Rear Shock'), ('grips', 'Grips'), ('pivot-bearings', 'Pivot Bearings'), ('front-shifter', 'Front Shifter'), ('rear-shifter', 'Rear Shifter'), ('front-shifter-cable', 'Front Shifter Cable'), ('rear-shifter-cable', 'Rear Shifter Cable')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
