# Generated by Django 2.1.7 on 2019-03-19 06:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geartracker', '0002_add_gear_type_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='default',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
