# Generated by Django 2.2.3 on 2019-09-19 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geartracker', '0003_add_default_bike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='title',
            field=models.CharField(default='Your Activity', max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='APIAccessTokens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('api', models.CharField(max_length=20)),
                ('title', models.CharField(default='Your Activity', max_length=100)),
                ('description', models.TextField(blank=True, max_length=6500, null=True)),
                ('access_token', models.TextField(blank=True, max_length=6500, null=True)),
                ('refresh_token', models.TextField(blank=True, max_length=6500, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apiaccesstokens_created_by', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='apiaccesstokens_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'APIs and Tokens',
            },
        ),
    ]
