# Generated by Django 2.2.3 on 2019-09-19 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geartracker', '0004_add_api_access_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiaccesstokens',
            name='subscription_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
