# Generated by Django 2.2.3 on 2019-09-19 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geartracker', '0005_add_api_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='gear_id',
            field=models.CharField(max_length=100, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='activity_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='apiaccesstokens',
            name='athlete_id',
            field=models.IntegerField(default=0),
        ),
    ]
