# Generated by Django 3.0.4 on 2020-03-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geartracker', '0006_add_api_object_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='activity',
            name='elevation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='apiaccesstokens',
            name='subscription_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='gear',
            name='elevation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='bike',
            name='distance',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='bike',
            name='elevation',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=11),
        ),
        migrations.AlterField(
            model_name='activity',
            name='activity_id',
            field=models.BigIntegerField(default=0),
        ),
    ]
